[project]
name = "storage"
version = "0.1.0"
description = "storage using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]==1.6.1",
]

[project.scripts]
storage = "storage.main:run"
run_crew = "storage.main:run"
train = "storage.main:train"
replay = "storage.main:replay"
test = "storage.main:test"
run_with_trigger = "storage.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
